### ISSUE TITLE
Add update and delete buttons for a survey 

### ISSUE THREAD

**Issue by Kayla-SA-W** [team-grilled-cheese/front-end#18]
For a survey that a user has created, show the update and delete buttons for user to update and delete that survey

**Comment by ssolmonson** [comment]
Research how editables from Ruby are used in Node.js/Mongoose. Or how to define a user owns the survey to only display update and remove buttons for those surveys the user owns.

**Comment by ssolmonson** [comment]
Close ref: 44a7053e79103f8a84153b093821065be950a1d8
